# Generated by Django 5.0.14 on 2025-05-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="fuel_type",
            field=models.CharField(
                choices=[
                    ("HY", "Hybrid"),
                    ("EC", "Electric"),
                    ("DS", "Diesel"),
                    ("GS", "Gasoline"),
                ],
                default="HY",
                max_length=2,
            ),
        ),
        migrations.DeleteModel(
            name="FuelType",
        ),
    ]
