# Generated by Django 5.0.14 on 2025-05-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0002_alter_vehicle_fuel_type_delete_fueltype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="vin",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
